use smql_ast::machine::MachineDefinition;

use crate::error::{CodegenError, CodegenResult};
use crate::rust_gen;

/// A generated output file with path and content.
#[derive(Debug, Clone)]
pub struct GeneratedFile {
    pub path: String,
    pub content: String,
}

/// Code generator that reads .smql files and produces Rust source.
pub struct CodeGenerator {
    machines: Vec<MachineDefinition>,
}

impl CodeGenerator {
    /// Create a generator from raw SMQL source text.
    pub fn from_source(source: &str) -> CodegenResult<Self> {
        let machines = smql_parser::parse_machines(source)
            .map_err(|e| CodegenError::Parse(e.to_string()))?;
        if machines.is_empty() {
            return Err(CodegenError::NoMachines);
        }
        Ok(Self { machines })
    }

    /// Create a generator from .smql files on disk.
    pub fn from_files(paths: &[&str]) -> CodegenResult<Self> {
        let mut machines = Vec::new();
        for path in paths {
            let source = std::fs::read_to_string(path)?;
            let parsed = smql_parser::parse_machines(&source)
                .map_err(|e| CodegenError::Parse(format!("{}: {}", path, e)))?;
            machines.extend(parsed);
        }
        if machines.is_empty() {
            return Err(CodegenError::NoMachines);
        }
        Ok(Self { machines })
    }

    /// Generate Rust source code. Returns one GeneratedFile per machine.
    pub fn generate_rust(&self) -> Vec<GeneratedFile> {
        self.machines
            .iter()
            .map(|def| {
                let module_name = rust_gen::to_snake_case(&def.name);
                GeneratedFile {
                    path: format!("{}.rs", module_name),
                    content: rust_gen::generate_machine_module(def),
                }
            })
            .collect()
    }

    /// Generate a single combined file with all machines as modules.
    pub fn generate_combined_rust(&self) -> String {
        let mut out = String::new();
        out.push_str("// Auto-generated by smql-codegen. Do not edit.\n\n");
        for def in &self.machines {
            out.push_str(&rust_gen::generate_machine_module(def));
            out.push('\n');
        }
        out
    }

    /// Get the parsed machine definitions.
    pub fn machines(&self) -> &[MachineDefinition] {
        &self.machines
    }
}
