[package]
name = "smql-engine-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
smql-ast = { path = "../smql-ast" }
smql-catalog = { path = "../smql-catalog" }
smql-storage = { path = "../smql-storage" }
smql-trail = { path = "../smql-trail" }
smql-timer = { path = "../smql-timer" }
smql-hooks = { path = "../smql-hooks" }
tokio = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
ulid = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
smql-parser = { path = "../smql-parser" }
smql-codegen = { path = "../smql-codegen" }
uuid = { version = "1", features = ["v4", "v7", "serde"] }
serde_json = { workspace = true }
